### ISSUE TITLE
Save Painters

### ISSUE THREAD

**Issue by tprovoost** [Icy-imaging/Icy-Kernel#259]
It think would be nice to be able to save painters without the necessity to use UBYTE mode.

I know it means we lose every mouse/key listener for the painter, but if we save every layer as an image and when we open it next time there are here, it would be very nice.

I think it is more important to have (next time we open an image) painters as images on the original sequence than a new sequence in UBYTE with painters rendered in it. 
That way you don't need to keep the original data and a rendered version with painters, just the original data.

What do you think ?

**Comment by Stephane-D** [comment]
Done
