### ISSUE TITLE
Optional startup arguments

### ISSUE THREAD

**Issue by ylemontag** [Icy-imaging/Icy-Kernel#303]
Hi,

It would be nice if it were possible to perform some actions in Icy (such as starting a plugin, opening a sequence) by passing optional arguments on the startup command line. Ex:

./icy.sh --start=myplugin -i myimage.tif

Such kind of feature would be very useful for interaction between Icy and other applications (ex: launching Icy from Matlab).

Thank you.

**Comment by icygithub** [comment]
Cher Stephane,

I tried to launch plugin using the method you described with no luck.
I noticed that the bash script icy.sh does not read the additional argument you are passing.

Any idea what is going wrong?

Thanks

**Comment by Stephane-D** [comment]
oh indeed the sh script does not consider extra inputs,n that might be the problem.
So indeed of using the .sh script, just copy its content :
`java -jar updater.jar  -x plugins.devName.pluginName myimage.tif`

**Comment by icygithub** [comment]
Thanks Stephane. Indeed, I have already tried the solution you suggested as follows:
java -jar updater.jar -x plugins.tprovoost.scripteditor myscript.js

Icy GUI is launched but the plugin is not kicked and the script does not execute.

**Comment by Stephane-D** [comment]
In fact you have to give the full class name of the plugin :
java -jar updater.jar -x plugins.tprovoost.scripteditor.main.ScriptEditorPlugin myscript.js

Current version of the script editor does not support command line opening file but i will update it for that !

**Comment by icygithub** [comment]
Interesting. Merci Stephane.
Any idea when will you be able to do that?

**Comment by Stephane-D** [comment]
I think i can do it today, I will post a message here when it will be ready :)

**Comment by Stephane-D** [comment]
I just updated the script editor, it should work now. Not that it does not yet support headless mode (mean that you can execute a script without having Icy GUI appearing at all).

**Comment by icygithub** [comment]
Great! It runs perfectly. Thanks Stephane.
I am planning to call icy iteratively inside a script, and thus as you anticipated headless mode would be preferable. I am currently implementing a rather simple and primitive logic to cope with the current situation. I appreciate if you keep me posted once you get the chance to support headless mode in the future.

**Comment by Stephane-D** [comment]
Unfortunately making it headless is another story, the Script Editor was not designed to work headless but i wonder if we can get it to work it by using a script block inside a protocol (which are compatible with headless mode).

**Comment by icygithub** [comment]
Yea, I understand that making it headless is not straightforward.
But I am wondering, if it is possible to let the javascript reads external arguments?
This would give great flexibility when calling the ScriptEditor plugin for a shell script.

Example:
java -jar updater.jar -x plugins.tprovoost.scripteditor.main.ScriptEditorPlugin myscript.js arg1 arg2 ..

**Comment by Stephane-D** [comment]
How you would interpret these extras arguments ?
just having variables named arg1, arg2... ?
Actually you can access them directly from the script with `Icy.getCommandLinePluginArgs()` method where the first entry [0] is the name of the script.

**Comment by icygithub** [comment]
Dear Stephane,

I was able to use Icy.getCommandLinePluginArgs() method to access the extra arguments.

I have the following questions:
+ I tried to print args[0] (name of the script) and it always turns out to be "null". Is it fine?
+ I tried to cast the extra arguments to "int" or "double" with no luck. Can you please show me how to do that?

Thanks :)

**Comment by Stephane-D** [comment]
Yeah args[0] is null as the ScripEditor "consume" it so it does not execute it several time (actually each time you launch the Script Editor plugin). Any plugin supporting command line operation should do that to avoid accidental multi execution of the command line parameters.
All arguments are in String format, if you want to transform them to int or double, just use the  Icy StringUtil.parseInt(..) / parseDouble(..) methods :)

**Comment by icygithub** [comment]
I see. Thanks :+1:
