### ISSUE TITLE
Save LUT in XML

### ISSUE THREAD

**Issue by adufour** [Icy-imaging/Icy-Kernel#335]
I have some imaging data stored via OME, but the format is missing a lot of info which I want to correct by myself. Since my sequence has 4 channels, it automatically loads as "Red/Green/Blue/Alpha" by default (all colors are wrong, and alpha is of course additionally weird).

I changed the channel names to the correct ones (this is stored in the XML), but changing the color type (e.g. from alpha to magenta) is not saved. I also think that LUT parameters (user min/max) should also be saved, because that's how the user wants to see the data.

Thanks !

Edit: Think about a "set as default" button...

**Comment by Stephane-D** [comment]
Done.
