### ISSUE TITLE
Artefacts with VTK Canvas on MacOS

### ISSUE THREAD

**Issue by tlecomte** [Icy-imaging/Icy-Kernel#467]
As soon as I switch from a 2D canvas to a 3D VTK Canvas, the Icy window slows down and is full of rendering artefacts: the background disappears, the 3D canvas stays on top of other windows...

![Icy](https://f.cloud.github.com/assets/44706/167725/244bad38-79e3-11e2-9284-6d5da31545f1.jpg)

**Comment by Stephane-D** [comment]
Solved with new OpenGL window incoming with Icy 1.8.0.0
