### ISSUE TITLE
Maximize in multiscreen environment

### ISSUE THREAD

**Issue by tlecomte** [Icy-imaging/Icy-Kernel#491]
Dear Icy devs,

I have two screens, on MacOS. I want to maximize Icy on the second screen. I grab the window in the first screen and drag it to the second screen, and then I click on the maximize button. Unfortunately the window gets maximized to the first screen, instead of the second !

Can you please fix that ? Thanks !

**Comment by Stephane-D** [comment]
It was definitely a bug in the OSX JVM which appears to be fixed on recent java 8 :)
