### ISSUE TITLE
ROI Polygon edition bug

### ISSUE THREAD

**Issue by Fab14** [Icy-imaging/Icy-Kernel#567]
Hi,

In the following case:

-win32
-original material for training
-no internet
- 1GB ram

the polygon creation, at some point, don't allow to add more than 2 points when creating the polygon.

Once in this state, even closing/opening new images let the app with the same problem

Seems very difficult to reproduce the bug !

:cake:

Fabrice

**Comment by Stephane-D** [comment]
Closed as the bug seems to really have disappeared in the latter version.
