### ISSUE TITLE
ROI set position and size from keyboard / video FPS shortcut

### ISSUE THREAD

**Issue by phcarl** [Icy-imaging/Icy-Kernel#610]
Dear all,
It would be cool to have the possibility to move (and increase the size of) a ROI by using the keyboard (by means of the arrow keys and one of its modifier like Alt).
Additionally it is quite cool to have the possibility to play a movie on time series as well as change the number of fps. Nevertheless the number of fps can be modified by using the mouse but not directly by typing the value since the field is latched.
I thank you very much in advance for considering these updates.
My best regards,
Philippe

**Comment by Stephane-D** [comment]
Roi modification from the keyboard is implemented !
When a ROI is selected :
Ctrl+Arrow keys = ROI set position (1 pixel step)
Ctrl+Shift+Arrow keys = ROI set position (10 pixels step)
Ctrl+Alt+Arrow keys = ROI set dimension (1 pixel step)
Ctrl+Alt+Shift+Arrow keys = ROI set dimension (10 pixel step)

I admit that using 3 modifiers at once (Ctrl+Alt+Shift) is kind of over complicated but we wanted to keep the T/Z navigation as default arrow keys action.
For the FPS editable field, there is unfortunately no easy workaround right now (problem of single focusable field) so i will close the issue in the state.
Don't hesitate to post remarks about it
