### ISSUE TITLE
Contrast stretching with fixed window size

### ISSUE THREAD

**Issue by oeway** [Icy-imaging/Icy-Kernel#619]
Hi Stephane,

As I discussed with you on the QIB conference, we would like to move the "bit window" with fixed size to view different range of grayscale. It would be better to add an anchor in the middle of the read line and blue line.

**Comment by Stephane-D** [comment]
Thanks for opening an issue about it, definitely a good way to remember ;)

**Comment by Stephane-D** [comment]
done.
