### ISSUE TITLE
catch OutOfMemoryError at high level

### ISSUE THREAD

**Issue by adufour** [Icy-imaging/Icy-Kernel#625]
Just a thought. Currently this is opening a bug report window (and eventually an email). Although sometimes there are optimisations possible, most of the time it's just a fact that the computer has not enough RAM to do (whatever process). Perhaps a nice message describing the problem in a user-friendly way and possible solutions (if available: e.g. check the JVM version/setting, etc.)

Additionally, perhaps an extra interface that plugins could implement to clean stuff when the issue is caught (like is done on mobile OSes for instance)

**Comment by Stephane-D** [comment]
I will change the report frame to a simple "failed" announce frame inviting the user to check the maximum memory parameter as indeed that is not a real error :)

About adding an interface for plugin, well i guess user could simply catch the OutOfMemory error for that specific case ;)
