### ISSUE TITLE
Detect (and warn) when a 64bit machine is running 32bit Java (and should upgrade)

### ISSUE THREAD

**Issue by adufour** [Icy-imaging/Icy-Kernel#637]
The current Icy statistics (as of this writing) show that there is a majority of Win32 systems running out there, more than Mac64 (perhaps understandably) but also more than Win64 (arguably less understandable). Although I agree there are quite old computers in research facilities, I doubt Win32 still wins, and would argue this is certainly due to Win64 machines unknowingly running a 32bit Java.

I suggest adding a detection + warning at Icy startup to check system version and tell the user that a 64bit JVM is available/preferred. This could be done on *nix based systems (Mac, Linux) with the `uname` command, and on windows with the `systeminfo` or `wmic` commands.

**Comment by Stephane-D** [comment]
Done (only for windows as that is where we meet the problem almost time).
