### ISSUE TITLE
Icy crashes when using VTK on OSX with Java7 or Java8.

### ISSUE THREAD

**Issue by ThomasWalter** [Icy-imaging/Icy-Kernel#638]
I am just starting with Icy. In a first test, I wanted to play around with some sample images I have, and in particular I used the elevation map plugin. Icy crashed without further information. 

I am using Mac, OS X 10.11.3

**Comment by Stephane-D** [comment]
Thanks for the report !
Elevation map uses VTK internally, which can make Icy crashes strongly (no message, just close).
Did you tried to use the classic VTK 3D volume view on a Z Stack to see if it crashes the same way ?

**Comment by ThomasWalter** [comment]
Yes, if I use the VTK 3D volume view on a stack, it crashes the same way indeed.

**Comment by Stephane-D** [comment]
I guess that is because you are using a java 7 or java 8, currently VTK works only with java 6 on OSX but that will be fixed in the next version of Icy. If you really need to use 3D views with VTK you can also revert to Java 6 on your system :
http://icy.bioimageanalysis.org/faq#33

**Comment by Stephane-D** [comment]
Ok, we finally sorted this one, Icy 1.8.0.0 will support VTK with java 7 or java 8 on newers OSX.
The drawback is that older version of OSX (<= 10.6.8) won't support VTK anymore...
Users using these systems need to keep Icy 1.7.3.0 if they really want to preserve VTK support :-/
