### ISSUE TITLE
Add Line / Polyline / Polygone 3D ROI

### ISSUE THREAD

**Issue by Stephane-D** [Icy-imaging/Icy-Kernel#639]

**Comment by Stephane-D** [comment]
Implemented with Icy 1.9.0.0

**Comment by imagejan** [comment]
> Implemented with Icy 1.9.0.0

Where can I get 1.9.0.0 ?

**Comment by Stephane-D** [comment]
Hi,

It's not yet released but you arrive as soon we fix the last remaining issues (OSX launcher mainly) ;)
And in fact it adds only Line / Polyline 3D, not polygon (this one almost already exists with Mesh3D).
