### ISSUE TITLE
Truncated dataset name in ROI Statistics

### ISSUE THREAD

**Issue by julienpontabry** [Icy-imaging/Icy-Kernel#646]
Hi folks,

I have an annoying issue about the dataset name: it gets truncated when the filename is too long (see the attached screenshot below).

![dataset_name_truncated](https://user-images.githubusercontent.com/404443/27838054-6b39e354-60e8-11e7-93a6-086c01d8cf11.png)

It would be useful to have arbitrary long names for dataset, as the filenames often contain information about an experiment.

Thanks!
Julien.

**Comment by adufour** [comment]
The issue is fixed in the latest update of the ROI Statistics plugin.
Thx for the report!

**Comment by julienpontabry** [comment]
Thanks Alexandre!
