### ISSUE TITLE
Plugin : constrained package name

### ISSUE THREAD

**Issue by Gpotier** [Icy-imaging/Icy-Kernel#655]
Hello,

I am currently working on the `ec-clem` plugin and I found out that `icy.plugin.PluginLoader` ignores every class not in the `plugins` package. I there a specific reason for this behaviour ? It is annoying since I would like to put our plugin's code under a package named after our organization.

Best regards.

**Comment by Stephane-D** [comment]
Hi,

Yeah we used that method to uniquely and quickly identify plugin class so the package should be formatted as follow:
 plugins.<dev_id>.xxx
Still you only need the *Plugin* class to be in that specific package, you can let all your other classes as you want.

Best,
