### ISSUE TITLE
Error reporting is missing stack strace

### ISSUE THREAD

**Issue by haesleinhuepf** [Icy-imaging/Icy-Kernel#656]
Hey Icy team,

I just received a bug report from \[Icy\] via email. However, it's not very helpful because it doesn't contain the stack trace... Could the error reporting tool be changed to also submit it?

Thanks!

Cheers,
Robert

That was the email I got:
```
Icy Version 2.0.3.0
Java(TM) SE Runtime Environment 1.8.0_231-b11 (64 bit)
Running on Mac OS X 10.14.6 (x86_64)
Max java memory : 17.2 GB

Comment:
Please type here your comment

java.lang.NullPointerException
```

**Comment by Stephane-D** [comment]
Hi @haesleinhuepf,

It's weird that you received this error as it comes from the "output" box of Icy and should only be notified to the Icy dev team, so you can forget it, it wasn't for you i think (we have to see why you received it though).
 
And normally, of course any bug report comes with the Stack Trace, when it's not the case it means something really wrong happened (or the error wasn't properly catch).

Best.

**Comment by haesleinhuepf** [comment]
Yes, I received another one with stack trace. And in general I like having that kind of error reporting!

I'll close this issue for now.
